# Use CentOS as the base image
FROM centos:latest

# Install any necessary packages
RUN yum update -y && \\\r\n yum install -y curl

# Define the default command
CMD ["bash"]

# .github/workflows/docker-build.yml
name: Build CentOS Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: docker/cache-action@v2
      with:
        path: /tmp/.buildx-cache

    - name: Build Docker image
      run: |
        docker build -t my-centos-image .

    - name: Push Docker image to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker tag my-centos-image ${{ secrets.DOCKER_USERNAME }}/my-centos-image:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-centos-image:latest
